# Generated by Django 2.2.5 on 2019-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
