# Generated by Django 2.2.5 on 2019-09-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20190925_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
