# Generated by Django 2.2.5 on 2019-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('typeof', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
