# Generated by Django 2.2.5 on 2019-10-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='transcid',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
