# Generated by Django 2.2.5 on 2019-10-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20191023_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
